services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-blog}
      POSTGRES_USER: ${DB_USER:-blog}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret123}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-blog} -d ${DB_NAME:-blog}"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    env_file: .env.docker        # <-- тут лежать твої EMAIL_* і DB_* для Docker
    working_dir: /code/mysite
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  web_migrate:
    extends:
      service: web
    command: python manage.py migrate --noinput

  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      web_migrate:
        condition: service_completed_successfully
